var p=this||self;function r(g,l){g=g.split(".");var k=p;g[0]in k||"undefined"==typeof k.execScript||k.execScript("var "+g[0]);for(var m;g.length&&(m=g.shift());)g.length||void 0===l?k[m]&&k[m]!==Object.prototype[m]?k=k[m]:k=k[m]={}:k[m]=l};r("get",function(g,l){w("GET",g,null,l)});r("syncGet",function(g){let l=new XMLHttpRequest;l.open("GET",g,!1);l.send();return l.responseText});r("post",function(g,l,k){w("POST",g,l,k)});function w(g,l,k,m){let q=new XMLHttpRequest;q.open(g,l,1);q.send(k);q.onload=()=>m(q.responseText)}function x(g){return document.getElementById(g)}r("getEl",x);function y(g){return document.createElement(g)}r("newEl",y);let C=y("style");C.innerHTML="template{display:none}";document.head.appendChild(C);
r("Reanet",function(g={}){function l(){this.g=[];this.h=(a,c)=>{for(let b=0;b<this.g.length;b++)this.g[b].h(a,c)};this.add=a=>{this.g.push(a)}}function k(a){let c=a.getAttributeNames(),b=[];for(let d=0;d<c.length;d++){var e=a.getAttribute(c[d]);e=new m(e);e.g&&(e.n=c[d],b.push(e))}0<b.length?(this.g=b,this.h=(d,f)=>{for(let h=0;h<this.g.length;h++){let n=this.g[h];n.h(d,f)&&a.setAttribute(n.n,n.u)}}):this.h=t}function m(a){var c=0,b=a.indexOf("{",c);this.u=a;if(-1<b){this.i=[];this.g={};for(this.l=
[];;){b=a.indexOf("{",c);if(-1==b){this.i.push(a.substring(c));break}this.i.push(a.substring(c,b));c=a.indexOf("}",b);b=a.substring(b+1,c);this.g[b]=b;this.l.push(b);c+=1}this.h=(e,d)=>{let f=!0;for(let h in this.g){let n=z(d?z(e,d):e,h);void 0==n&&(n=h);this.g[h]!=n&&(f=!1,this.g[h]=n)}if(f)return!1;e=this.i[0];for(d=1;d<this.i.length;d++)e+=this.g[this.l[d-1]]+this.i[d];this.u=e;return!0}}else this.h=t}function q(a){let c=a.textContent.trim();-1<c.indexOf("{",0)?(this.i=a,this.g=new m(c),this.h=
(b,e)=>{this.g.h(b,e)&&(this.i.textContent=this.g.u)}):this.h=t}function D(a,c){this.g=[];this.i=c;a.A=a.style.display;a.o=!0;this.add=b=>{this.g.push(b)};this.h=(b,e)=>{if(eval(this.i)){a.o||(a.style.display=a.A,a.o=!0);for(let d=0;d<this.g.length;d++)this.g[d].h(b,e)}else a.o&&(a.style.display="none",a.o=!1)}}function E(a,c){this.i=a;this.g={};this.F=A(v(a.childNodes));c=c.split(":");this.B=c[1];this.l=c[0];this.i.innerHTML="";this.D=b=>{if(b in this.g)return this.g[b];let e=v(this.F),d=new l;d.m=
e;d.j=!1;for(let f=0;f<e.length;f++)u(e[f],d);return this.g[b]=d};this.h=b=>{var e=b[this.B];if(e){let d,f;for(f=0;f<e.length;f++){let h=b[this.l];b[this.l]=e[f];d=this.D(f);d.h(b,void 0);b[this.l]=h}for(f=0;f<e.length;f++)if(d=this.g[f],!d.j)for(d.j=!0,b=0;b<d.m.length;b++)this.i.appendChild(d.m[b]);for(e=Object.keys(this.g).length;f<e;f++)if(d=this.g[f],d.j){for(b=0;b<d.m.length;b++)this.i.removeChild(d.m[b]);d.j=!1}}}}function F(a){a=G(a);this.s=a.s;if(a.v)for(let c=0;c<a.v.length;c++)eval(a.v[c].textContent);
this.g=()=>v(this.s);this.placeTo=(c,b)=>{let e=new l,d=x(c),f=this.g(),h;if(b){for(h=0;h<f.length;h++)u(f[h],e);e.h(b,void 0);for(h=0;h<f.length;h++)d.appendChild(f[h])}else for(h=0;h<f.length;h++)u(f[h],e),d.appendChild(f[h]);e.id=c;return d.G=e}}const t=()=>!1,H=new DOMParser;this.l={};this.model=g;this.j=[];this.g=!1;let A=a=>{let c=[];for(let b=0;b<a.length;b++){let e=a[b];(e.childNodes&&e.childNodes.length||"#text"!=e.nodeName||/\S/.test(e.textContent))&&c.push(e)}return c},G=a=>{a=H.parseFromString(a,
"text/html");return{v:a.scripts,s:A(a.body.childNodes)}},v=a=>{let c=[];for(let b=0;b<a.length;b++)c.push(a[b].cloneNode(!0));return c},B=(a,c)=>{let b=a.getAttribute(c);b&&a.removeAttribute(c);return b},u=(a,c)=>{if(a.childNodes&&a.childNodes.length){var b=new k(a);b.h&&c.add(b);if(b=B(a,"if"))b=new D(a,b),c.add(b),c=b;if(b=B(a,"for"))c.add(new E(a,b));else for(b=0;b<a.childNodes.length;b++)u(a.childNodes[b],c)}else/\S/.test(a.textContent)&&(a=new q(a),a.h!=t&&c.add(a))},z=(a,c)=>{c=c.split(".");
let b=0;for(;b<c.length;b++){if(!a)return;a=a[c[b]]}return a};this.placeTo=(a,c)=>{a=this.l[c].placeTo(a,this.model);this.j.push(a);return this};this.destroy=a=>{let c=x(a);if(c){if(c.G)for(let b=this.j.length-1;0<=b;--b)this.j[b].id==a&&this.j.splice(b,1);c.innerHTML=""}};this.update=()=>{for(let a=0;a<this.j.length;a++){let c=this.j[a];c.C||c.h(this.model)}return this};this.lock=a=>this.i(!0,a);this.unlock=a=>this.i(!1,a);this.i=(a,c)=>{c?x(c).H.C=a:this.g=a;return this};this.set=(a,c)=>{this.model[a]=
c;this.g||this.update();return this};g=(()=>{let a=document.getElementsByTagName("template"),c={};for(let b=0;b<a.length;b++)c[a[b].getAttribute("name")]=a[b].innerHTML;return c})();for(let a in g)this.l[a]=new F(g[a])});
